// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1yNaVRcH2MOSZnkQikWYXphGPDtaoxIQ',
    appId: '1:26516054189:web:fe52ecad581d92b755e624',
    messagingSenderId: '26516054189',
    projectId: 'sunil-medical-store',
    authDomain: 'sunil-medical-store.firebaseapp.com',
    storageBucket: 'sunil-medical-store.firebasestorage.app',
    measurementId: 'G-D8K2ZPGSP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCCKPbGyGOvraXbBvMw9zvdJCD8EH4LNw',
    appId: '1:26516054189:android:a7d21ee77e428d9e55e624',
    messagingSenderId: '26516054189',
    projectId: 'sunil-medical-store',
    storageBucket: 'sunil-medical-store.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjH01ysFFWdtRNMlNqtP_ZRbYep-5v9Z0',
    appId: '1:26516054189:ios:a905418db20674d355e624',
    messagingSenderId: '26516054189',
    projectId: 'sunil-medical-store',
    storageBucket: 'sunil-medical-store.firebasestorage.app',
    iosBundleId: 'com.example.sunilMedicalStore',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjH01ysFFWdtRNMlNqtP_ZRbYep-5v9Z0',
    appId: '1:26516054189:ios:a905418db20674d355e624',
    messagingSenderId: '26516054189',
    projectId: 'sunil-medical-store',
    storageBucket: 'sunil-medical-store.firebasestorage.app',
    iosBundleId: 'com.example.sunilMedicalStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1yNaVRcH2MOSZnkQikWYXphGPDtaoxIQ',
    appId: '1:26516054189:web:577cde4675addd4355e624',
    messagingSenderId: '26516054189',
    projectId: 'sunil-medical-store',
    authDomain: 'sunil-medical-store.firebaseapp.com',
    storageBucket: 'sunil-medical-store.firebasestorage.app',
    measurementId: 'G-BE17V3EGV4',
  );
}
